<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86</Platforms>
    <RootNamespace>ViewVb</RootNamespace>
    <TargetFrameworks>
      net48;
    </TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MainWindow.xaml.vb" />
  </ItemGroup>

</Project>
